# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AssemblyTableview' do
   pod ‘ComponentTableView’, :podspec => 'ComponentTableView.podspec'
end

target 'AssemblyTableviewTests' do

end

target 'AssemblyTableviewUITests' do

end

